#!usr/bin/env bash
#Script that displays 1-20 using case

i=0

while [ $((i++)) -lt 20 ]; do
	echo $i
	case $i in 4)
		echo badluck from China
			;;
	9)
		echo badluck from Japan
			;;
	17)
		echo bad luck from Italy
			;;
	esac
done
